### PR TITLE
Expose logged in state

### PR DESCRIPTION
**Pull request by adamsilver**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
can't we do this inside a js library? :/ :-1:

**Comment by matthew-andrews** [comment]
also need to make sure that we only put this kind of data on pages that are varied on login status

**Comment by matthew-andrews** [comment]
also also `nextData` is exactly the kind of global object we've tried before not to bring into Next.  (On FT.com they use `window.FT`)

**Comment by aintgoin2goa** [comment]
@matthew-andrews all pages are varied on login status

I agree with the other stuff - though.  I thought this would just be a html-attribute?

**Comment by adamsilver** [comment]
Just agreed with @matthew-andrews that we would expose a single variable nextIsAnonymous. Rationale for what it's worth: best to avoid a DOM read for performance.  Putting it all in data attributes doesn't solve the `window.FT` issues; you can see `documentElement` getting bigger and bigger :(

**Pull request merged**
