### PR TITLE
Ignore everything in Bower

### PR DESCRIPTION
**Pull request by i-like-robots**
As suggested by @ironsidevsquincy we should probably just include next-express as a Bower dependency in our apps instead of manually adding and managing this module's front-end dependencies within each app's bower.json.

- https://github.com/Financial-Times/next-engels/pull/253
- https://github.com/Financial-Times/next-dobi/pull/486
- https://github.com/Financial-Times/next-article/pull/516

### CODE REVIEW

**Comment by matthew-andrews** [comment]
we regularly have components that are both bower and npm modules, don't think this is particularly contentious.

**Comment by matthew-andrews** [comment]
⇔ the layout dependency checks are removed from NBT :wink:

**Comment by ironsidevsquincy** [comment]
:+1:

**Comment by i-like-robots** [comment]
> ⇔ the layout dependency checks are removed from NBT :wink:

¯\(°_o)/¯

**Pull request merged**
