### PR TITLE
oops, forgot it was a manual update

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by keirog** [comment]
:+1:

**Comment by ironsidevsquincy** [comment]
doesn't `"Financial-Times/next-beacon-node-client#^2.1.3` work?

**Comment by keirog** [comment]
I was under the impression you couldn't do semver stuff in npm github dependencies--just tags and commit hashes. Hopefully am wrong though

**Comment by matthew-andrews** [comment]
@ironsidevsquincy — nope that only works for bower, not npm :disappointed:

**Pull request merged**
