### PR TITLE
Barrier beacon

### PR DESCRIPTION
**Pull request by aintgoin2goa**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
:+1:

**Comment by matthew-andrews** [comment]
oh this was kind of a breaking change…… now apps won't start without `BEACON_URL`s…… annoying for APIs…… :/

**Comment by ironsidevsquincy** [comment]
yup https://travis-ci.org/Financial-Times/next-dobi/builds/68185379

**Comment by matthew-andrews** [comment]
not really a problem thoguh… those should probbaly set their `withBarriers` option to be false

**Comment by matthew-andrews** [comment]
@ironsidevsquincy dobi can probably have `withBarriers: false` can't it @aintgoin2goa ?

**Comment by matthew-andrews** [comment]
i'm going to do that for next-redirector

**Comment by matthew-andrews** [comment]
grr still crashes

**Comment by matthew-andrews** [comment]
@aintgoin2goa can we roll back this change for now until this: https://github.com/Financial-Times/next-beacon-node-client/issues/9 is fixed?

**Pull request merged**
