### PR TITLE
Serve hashed assets from router

### PR DESCRIPTION
**Pull request by adgad**
/cc @wheresrhys @richard-still-ft @commuterjoy

### CODE REVIEW

**Comment by commuterjoy** [comment]
Not the comfortable with plugging the router in to non heroku domains. Would much rather we just have a assets.ft.com domain for the short term.

**Comment by adgad** [comment]
Will do here for now then sort out a proper route for it.

**Comment by adgad** [comment]
Proposed solution @commuterjoy @matthew-andrews @richard-still-ft :

* Add a basic express app to next-hashed assets. This will allow us to set cache headers etc.
* Push up to heroku (although has to be done synchronously before deploying app)
* Get next-geebee to point to app

**Comment by matthew-andrews** [comment]
@commuterjoy 

> Not the comfortable with plugging the router in to non heroku domains. Would much rather we just have a assets.ft.com domain for the short term.

why?

**Pull request merged**
