### PR TITLE
added internal capi to service list

### PR DESCRIPTION
**Pull request by wheresrhys**

### CODE REVIEW

**Comment by matthew-andrews** [comment]
no!

**Comment by matthew-andrews** [comment]
we should never use this in production

**Comment by wheresrhys** [comment]
it is in production https://github.com/Financial-Times/next-url-mapper/blob/master/src/config.js - I did think it was a bit weird it was there

**Comment by matthew-andrews** [comment]
ought to be fixed there then :wink:

**Comment by wheresrhys** [comment]
`http://api.ft.com/site/v1/navigations/ft-uk` doesn't exist which is why this url is used.

**Comment by matthew-andrews** [comment]
I emailed CAPI but ok for now

😔

**Pull request merged**
