### PR TITLE
exposing flags to css

### PR DESCRIPTION
**Pull request by wheresrhys**
To tackle css only bugs (like the current image service svg problem). Only exposing offy flags for the time being. 

@adgad @matthew-andrews

### CODE REVIEW

**Comment by ironsidevsquincy** [comment]
any benefit of data attrs over classes?

**Comment by matthew-andrews** [comment]
precedent…  we use data attrs a lot…  i was uncomfortable at first but iirc they have the same specificity so doesn't really matter…

**Comment by ironsidevsquincy** [comment]
just thinking about accessing them in older browsers

**Comment by wheresrhys** [comment]
the `~=` selector works way back to ie7 (which surprised me when I found out). I prefer data attributes for on/offy things or things where the alternative is a long list of name-spaced classes. Neater and the intent is a bit clearer I think.

**By the way, no-one merge this yeat as it'll probably make it slightly harder to roll-out a quick fix for today's user-testing**

**Comment by ironsidevsquincy** [comment]
wow, attribute selectors go down to ie7, really thought it would be higher than that. I take it all back, what a great browser

**Pull request merged**
