### PR TITLE
changing paragraphs helper

### PR DESCRIPTION
**Pull request by aintgoin2goa**
I was struggling to use this helper in the way I wanted - I think this makes it easier to understand

### CODE REVIEW

**Comment by matthew-andrews** [comment]
What's the support for body as arrays for?

Would you mind also updating the example [on the `README.md`](https://github.com/Financial-Times/next-express#viewsmainhtml)?

**Comment by aintgoin2goa** [comment]
the body was coming to me as an array - no idea why...

**Comment by aintgoin2goa** [comment]
ok, @matthew-andrews readme is updating can I merge?

**Comment by matthew-andrews** [comment]
:+1:

**Pull request merged**
